### ISSUE TITLE
推荐的硬件知识分享博主

### ISSUE THREAD

**Issue by xingdeshoumin** [DJTU-RM-TOE/DJTU-RM-TOE#1]
硬件底层公式推导， 容易理解
https://www.zhihu.com/people/ying-jian-gong-cheng-shi-lian-cheng-zhi-lu/posts?page=2

**Comment by evencewu** [comment]
> 硬件底层公式推导， 容易理解 https://www.zhihu.com/people/ying-jian-gong-cheng-shi-lian-cheng-zhi-lu/posts?page=2

感谢，已收录
